// Action types:
export const POST_MESSAGE = 'user/POST_MESSAGE',
					   POST_REPLY = 'user/POST_REPLY',
					   SELECT_MESSAGE = 'user/SELECT_MESSAGE',
					   VIEW_PROFILE = 'user/VIEW_PROFILE',
					   GET_CONVERSATION_LIST = 'user/GET_CONVERSATION_LIST',
					   GET_CONVERSATION = 'user/GET_CONVERSATION';

