// Action types:
export const POST_MESSAGE = 'user/POST_MESSAGE',
					   POST_REPLY = 'user/POST_REPLY',
					   SELECT_MESSAGE = 'user/SELECT_MESSAGE',
					   VIEW_PROFILE = 'user/VIEW_PROFILE',
					   GET_CONVERSATION_LIST = 'user/GET_CONVERSATION_LIST',
					   GET_CONVERSATION = 'user/GET_CONVERSATION',
					   GET_CONTACTS = 'user/GET_CONTACTS',
					   ADD_CONTACT = 'user/ADD_CONTACT',
					   INVITE_NEW_CONTACT = 'user/INVITE_NEW_CONTACT',
					   TOGGLE_PROFILE_EDITOR = 'user/TOGGLE_PROFILE_EDITOR',
					   TOGGLE_CONVERSATION_LIST = 'user/TOGGLE_CONVERSATION_LIST',
					   TOGGLE_NEW_CONVERSATION = 'user/TOGGLE_NEW_CONVERSATION',
					   TOGGLE_LOGOUT_BUTTON = 'user/TOGGLE_LOGOUT_BUTTON',
					   SAVE_PROFILE_CHANGES = 'user/SAVE_PROFILE_CHANGES';

